project_id = "jlsoiujwcjgmvijcmvas"

[functions.discover-jobs]
verify_jwt = false

[functions.parse-cv]
verify_jwt = false

[functions.match-job]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false
