// Viability test: generate a text-based PDF inside a Deno edge function using pdf-lib.
// pdf-lib is pure JS with no DOM/canvas dependency — unlike jsPDF which requires a browser.
// If this function returns a valid PDF blob, server-side PDF generation is confirmed viable
// for use in scheduled-automation and tailor-cv-for-job.
//
// Deploy: supabase functions deploy test-pdf-generation
// Invoke:
//   curl -X POST https://<project>.supabase.co/functions/v1/test-pdf-generation \
//     -H "Authorization: Bearer <service-role-key>" \
//     -H "Content-Type: application/json" \
//     -d '{"name":"Jane Doe","jobTitle":"Software Engineer","company":"Acme Corp"}' \
//     --output test-output.pdf
//   open test-output.pdf  (should open a 1-page PDF with the applicant details)
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { name = "Test Candidate", jobTitle = "Software Engineer", company = "Test Corp" } =
      await req.json().catch(() => ({}));

    // ── Create PDF ─────────────────────────────────────────────────────────────
    const doc = await PDFDocument.create();
    const page = doc.addPage([595, 842]); // A4 in points (72 dpi)
    const { width, height } = page.getSize();

    const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
    const fontReg = await doc.embedFont(StandardFonts.Helvetica);

    const margin = 56;
    let y = height - margin;

    // Name header
    page.drawText(name, {
      x: margin,
      y,
      size: 24,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.1),
    });
    y -= 30;

    // Horizontal rule
    page.drawLine({
      start: { x: margin, y },
      end: { x: width - margin, y },
      thickness: 1,
      color: rgb(0.7, 0.7, 0.7),
    });
    y -= 20;

    // Application context
    page.drawText(`Tailored for: ${jobTitle} at ${company}`, {
      x: margin,
      y,
      size: 12,
      font: fontReg,
      color: rgb(0.35, 0.35, 0.35),
    });
    y -= 30;

    // Section: Summary
    page.drawText("Professional Summary", { x: margin, y, size: 13, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
    y -= 18;
    const summaryText =
      `This PDF was generated server-side inside a Supabase Edge Function (Deno runtime) ` +
      `using pdf-lib@1.17.1 — a pure-JavaScript PDF library with no DOM or canvas dependency. ` +
      `If you can open and read this file, server-side PDF generation is confirmed viable ` +
      `for tailor-cv-for-job and the scheduled-automation pipeline.`;

    // Word-wrap at ~80 chars per line
    const words = summaryText.split(" ");
    let line = "";
    const lineHeight = 16;
    const maxWidth = width - margin * 2;
    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      const w = fontReg.widthOfTextAtSize(candidate, 11);
      if (w > maxWidth && line) {
        page.drawText(line, { x: margin, y, size: 11, font: fontReg, color: rgb(0.2, 0.2, 0.2) });
        y -= lineHeight;
        line = word;
      } else {
        line = candidate;
      }
    }
    if (line) {
      page.drawText(line, { x: margin, y, size: 11, font: fontReg, color: rgb(0.2, 0.2, 0.2) });
      y -= lineHeight;
    }
    y -= 10;

    // Section: Skills (sample)
    page.drawText("Key Skills", { x: margin, y, size: 13, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
    y -= 18;
    const skills = ["TypeScript", "React", "Node.js", "Supabase", "PostgreSQL", "Deno"];
    for (const skill of skills) {
      page.drawText(`• ${skill}`, { x: margin + 10, y, size: 11, font: fontReg, color: rgb(0.2, 0.2, 0.2) });
      y -= lineHeight;
    }
    y -= 10;

    // Footer
    const generatedAt = new Date().toISOString();
    page.drawText(`Generated by ApplyPilot edge function · ${generatedAt}`, {
      x: margin,
      y: 30,
      size: 8,
      font: fontReg,
      color: rgb(0.6, 0.6, 0.6),
    });

    // Serialize
    const pdfBytes = await doc.save();

    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="test-resume-${Date.now()}.pdf"`,
        "X-PDF-Library": "pdf-lib@1.17.1",
        "X-Runtime": "Deno",
      },
    });
  } catch (err) {
    console.error("test-pdf-generation error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : String(err) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
